### ISSUE TITLE
Exception while loading subtitles

### ISSUE THREAD

**Issue by Mudb0y** [mediasplashapp/mediasplash#9]
I'm attempting to view an anime and get a traceback in the log when it tries to load the subtitles.
Here's the part of the log leading up to the crash.

INFO: handler: log_handler: 2023-11-18 22:19:04,266.
vd Using hardware decoding (d3d11va-copy).
INFO: handler: log_handler: 2023-11-18 22:19:04,363.
cplayer AO: [wasapi] 48000Hz stereo 2ch float
INFO: handler: log_handler: 2023-11-18 22:19:04,371.
cplayer VO: [gpu] 1920x1080 p010
ERROR: core: exchandler: 2023-11-18 22:19:04,555.
Traceback (most recent call last):
  File "core.py", line 253, in onLoadFile
  File "gui\media_panel.py", line 59, in doLoadFile
  File "subtitles\handler.py", line 111, in load
  File "subtitles\reader.py", line 28, in generate_subtitles
  File "subprocess.py", line 647, in getoutput
  File "subprocess.py", line 628, in getstatusoutput
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] The handle is invalid

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Need more info, what's the media format? Is it mp4 or mkv? The subtitle used is an external or internal one? As in, is the subtitle inside the video itself or did you add it as a seprate file? If external what's the subtitle format, ass/ssa/etc

**Comment by Mudb0y** [comment]
Here's the full log.

INFO: core: main: 2023-11-18 22:18:54,527.
running on Windows-10-10.0.22631-SP0
INFO: core: main: 2023-11-18 22:18:54,527.
python version: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
INFO: core: main: 2023-11-18 22:18:54,527.
wx version: 4.1.1 msw (phoenix) wxWidgets 3.1.5
INFO: core: main: 2023-11-18 22:18:54,527.
machine name: AMD64
INFO: handler: log_handler: 2023-11-18 22:19:04,111.
cplayer (+) Video --vid=1 (*) 'HEVC-10bit' (hevc 1920x1080 23.976fps)
INFO: handler: log_handler: 2023-11-18 22:19:04,111.
cplayer (+) Audio --aid=1 --alang=jpn (*) 'Opus' (opus 2ch 48000Hz)
INFO: handler: log_handler: 2023-11-18 22:19:04,112.
cplayer (+) Subs  --sid=1 --slang=eng (*) 'MK' (ass)
INFO: handler: log_handler: 2023-11-18 22:19:04,112.
display-tags File tags:
INFO: handler: log_handler: 2023-11-18 22:19:04,112.
display-tags Title: [Aeenald] Himouto! Umaru-chan - S01E01 [BDRip 1080p HEVC-10bit Opus]
INFO: handler: log_handler: 2023-11-18 22:19:04,266.
vd Using hardware decoding (d3d11va-copy).
INFO: handler: log_handler: 2023-11-18 22:19:04,363.
cplayer AO: [wasapi] 48000Hz stereo 2ch float
INFO: handler: log_handler: 2023-11-18 22:19:04,371.
cplayer VO: [gpu] 1920x1080 p010
ERROR: core: exchandler: 2023-11-18 22:19:04,555.
Traceback (most recent call last):
  File "core.py", line 253, in onLoadFile
  File "gui\media_panel.py", line 59, in doLoadFile
  File "subtitles\handler.py", line 111, in load
  File "subtitles\reader.py", line 28, in generate_subtitles
  File "subprocess.py", line 647, in getoutput
  File "subprocess.py", line 628, in getstatusoutput
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] The handle is invalid

**Comment by Mudb0y** [comment]
The issue is fixed after trying the latest version.
